project:
  type: website
  output-dir: docs

website:
  site-url: https://alecfishbach.github.io/personal-website
  title: "Alec Fishbach"
  description: "Research, systems, and machine learning"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: writing.qmd
        text: Writing
      - href: cv.qmd
        text: CV
  page-footer:
    left: "Â© 2026 Alec Fishbach"
    right:
      - icon: github
        href: https://github.com/YOUR_GITHUB
      - icon: twitter
        href: https://twitter.com/YOUR_HANDLE

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true

